# Generated by Django 2.1.3 on 2018-12-11 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0007_maillot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maillot',
            name='image',
            field=models.ImageField(default='static/images/nike_air.jpeg', upload_to='static/images/maillots_pictures'),
        ),
    ]
