# Generated by Django 2.1.3 on 2018-12-11 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0008_auto_20181211_1443'),
    ]

    operations = [
        migrations.RenameField(
            model_name='maillot',
            old_name='image',
            new_name='maillot_picture',
        ),
    ]
