# Generated by Django 2.1.3 on 2018-12-11 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0009_auto_20181211_1451'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maillot',
            name='maillot_picture',
            field=models.ImageField(default='static/images/nike_air.jpeg', upload_to='static/images/maillot_pictures'),
        ),
    ]
